spring:
  application:
    name: Movie Reservation System

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/movie_reservation_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
    open-in-view: false


  flyway:
    enabled: true

  cache:
    type: redis

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  sql:
    init:
      mode: always

logging:
  level:
    # Hibernate SQL statements
    org.hibernate.SQL: WARN
    # Hibernate bind parameters
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

server:
  port: 8080

#pc:
#  address: 0.0.0.0
#  port: 8081

jwt:
  secret: 6c26c77b32d00771d60ebb853e59115bfb4facf5cbedf3029afc2c8f4d89ab7e
  expiration: 3600000                     # 1h

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: method

cors:
  allowed-origins:
    - http://localhost:8080
    - https://your-production-domain.com
  max-age: 3600